In [23]:
import pandas as pd
import os

In [24]:
roll="1024170298"

In [25]:
fixed_entries = [
{"question": "what is the annual fee", "answer": "The annual fee is Rs 500.",
"keywords": "fee cost price charge", "category": "billing"},
{"question": "how to reset password", "answer": "Go to Settings > Reset Password.",
"keywords": "password reset login", "category": "account"},
{"question": "what are your working hours", "answer": "We are open 9 AM to 5 PM.",
"keywords": "hours timing open time", "category": "general"},
{"question": "how can i pay the fee", "answer": "You can pay via UPI, card, or net banking.",
"keywords": "pay payment upi fee", "category": "billing"},
]

In [26]:
categories = ["billing", "account", "general"]

last_two = [int(d) for d in str(roll)[-2:]]

custom_entries = []

for d in last_two:

    category = categories[d % 3]

    if category == "billing":

        question = "how can i check my payment status"
        answer = "You can check your payment status in the billing section."
        keywords = "payment status billing"

    elif category == "account":

        question = "how do i update my registered mobile number"
        answer = "Go to Account Settings and update your registered mobile number."
        keywords = "mobile number account update"

    else:

        question = "where can i find the latest service updates"
        answer = "You can find the latest service updates on the official updates page."
        keywords = "updates service latest"

    custom_entries.append({
        "question": question,
        "answer": answer,
        "keywords": keywords,
        "category": category
    })

In [27]:
final_entries=fixed_entries+custom_entries
df=pd.DataFrame(final_entries)
df

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing
4,how can i check my payment status,You can check your payment status in the billi...,payment status billing,billing
5,where can i find the latest service updates,You can find the latest service updates on the...,updates service latest,general

In [28]:
def score_query(query, df):


    query_words = query.lower().split()

    results = []

    for index, row in df.iterrows():

        keywords = row["keywords"].lower().split()


        score = sum(1 for word in keywords if word in query_words)

        if score > 0:
            results.append({
                "question": row["question"],
                "answer": row["answer"],
                "category": row["category"],
                "score": score
            })


    results = sorted(results, key=lambda x: x["score"], reverse=True)

    return results

query = input("Enter your query: ")

results = score_query(query, df)

print(results)

[]

In [29]:
def same_category(category_name ,df):
  return df[df["category"].str.lower()==category_name.lower()]
personalized_category=custom_entries[0]["category"]
print("Category Selected :",personalized_category)

Category Selected : billing

In [30]:
idx=int(input("Enter the idx of the question"))
print("Selected question: ")
print(df.loc[idx,"question"])
new_key=input("Enter the new keyword: ")
df.loc[idx,"keywords"]=(
    df.loc[idx,"keywords"] +" " + new_key

)
print("Updated FAQ:")
print(df.loc[idx])
filename=roll +"_faq_data.csv"
df.to_csv(filename,index=False)
print("Updated dataframe saved as: ",filename)

Selected question:
what are your working hours
Updated FAQ:
question            what are your working hours
answer                We are open 9 AM to 5 PM.
keywords    hours timing open time office hours
category                                general
Name: 2, dtype: object
Updated dataframe saved as:  1024170298_faq_data.csv

In [31]:
import os

print(os.getcwd())

/Users/apple/Desktop/files/UCS420/assignment-4

In [32]:
print(os.listdir())

['ASSIGNMENT4.ipynb', '1024170298_faq_data.csv']

In [33]:
try:
    from google.colab import files
    files.download(filename)
except ImportError:
    # Not running in Colab: the CSV is already saved in the working directory
    print("Not running in Colab, file saved locally at:", os.path.abspath(filename))

Not running in Colab, file saved locally at: /Users/apple/Desktop/files/UCS420/assignment-4/1024170298_faq_data.csv

In [34]:
df.groupby("category")["question"].count()

category
account    1
billing    3
general    2
Name: question, dtype: int64

In [35]:
df

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time office hours,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing
4,how can i check my payment status,You can check your payment status in the billi...,payment status billing,billing
5,where can i find the latest service updates,You can find the latest service updates on the...,updates service latest,general

In [36]:
def score_query_with_ties(query, df):

    query_words = query.lower().split()

    results = []


    for index, row in df.iterrows():

        keywords = row["keywords"].lower().split()

        score = sum(1 for word in keywords if word in query_words)

        if score > 0:
            results.append({
                "question": row["question"],
                "answer": row["answer"],
                "category": row["category"],
                "score": score
            })


    if not results:
        print("No matching FAQ found.")
        return

    highest_score = max(result["score"] for result in results)


    best_matches = [
        result for result in results
        if result["score"] == highest_score
    ]


    if len(best_matches) > 1:

        print("\nTie detected!")
        print("Highest score:", highest_score)

        for result in best_matches:
            print("\nQuestion:", result["question"])
            print("Answer:", result["answer"])
            print("Category:", result["category"])

    else:

        print("\nBest match:")
        print("Question:", best_matches[0]["question"])
        print("Answer:", best_matches[0]["answer"])
        print("Category:", best_matches[0]["category"])

In [37]:
# Query that produces a tie ("fee" matches two billing FAQs equally)
query1 = "the fee"
print("Query:", query1)
score_query_with_ties(query1, df)

# Query with no match
query2 = "hello world"
print("\nQuery:", query2)
score_query_with_ties(query2, df)

Query: the fee

Tie detected!
Highest score: 1

Question: what is the annual fee
Answer: The annual fee is Rs 500.
Category: billing

Question: how can i pay the fee
Answer: You can pay via UPI, card, or net banking.
Category: billing

Query: hello world
No matching FAQ found.