
# UCS420 Assignment 3 – Pandas

**Name:** Pranav Garg <br>
**Roll Number:** 1024170298

**Q1: Create Dataset**

In [1]:
import pandas as pd
data = {'Tid' : range(1,11), 'Refund':['Yes','No','No','Yes','No','No','Yes','No','No','No'],'Marital Status':['Single','Married','Single','Married','Divorced','Married','Divorced','Single','Married','Single'],'Taxable Income':['125k','100k','70k','120k','95k','60k','220k','85k','75k','90k'],'Cheat':['No','No','No','No','Yes','No','No','Yes','No','Yes']}

In [2]:
df = pd.DataFrame(data)
df

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125k    No
1    2     No        Married           100k    No
2    3     No         Single            70k    No
3    4    Yes        Married           120k    No
4    5     No       Divorced            95k   Yes
5    6     No        Married            60k    No
6    7    Yes       Divorced           220k    No
7    8     No         Single            85k   Yes
8    9     No        Married            75k    No
9   10     No         Single            90k   Yes

**Q2: Locate Specific Rows in the DataFrame**

In [3]:
df.iloc[[0,4,7,8]]

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125k    No
4    5     No       Divorced            95k   Yes
7    8     No         Single            85k   Yes
8    9     No        Married            75k    No

**Q3.1: Select Rows from Index 3 to 7**

In [4]:
df.iloc[3:8]

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120k    No
4    5     No       Divorced            95k   Yes
5    6     No        Married            60k    No
6    7    Yes       Divorced           220k    No
7    8     No         Single            85k   Yes

**Q3.2: Select Rows 4–8 and Columns 2–4**

In [5]:
df.iloc[4:9,2:5]

  Marital Status Taxable Income Cheat
4       Divorced            95k   Yes
5        Married            60k    No
6       Divorced           220k    No
7         Single            85k   Yes
8        Married            75k    No

**Q3.3: Select All Rows with Columns 1–3**

In [6]:
df.iloc[:,1:4]

  Refund Marital Status Taxable Income
0    Yes         Single           125k
1     No        Married           100k
2     No         Single            70k
3    Yes        Married           120k
4     No       Divorced            95k
5     No        Married            60k
6    Yes       Divorced           220k
7     No         Single            85k
8     No        Married            75k
9     No         Single            90k

**Q4: Load the CSV File and Display First 5 Rows**

In [7]:
df1 = pd.read_csv('Iris.csv')
df1.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

**Q5: Remove Row 4 and Column 3 from the Dataset**

In [8]:
df1.drop(index=4, columns=df1.columns[3], inplace=True)
df1

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

**Q6: Create the Employee Dataset**

In [9]:
df2=pd.read_csv('employees.csv')
df2

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

**Q6(a): Check the Number of Rows and Columns**

In [10]:
df2.shape

(5, 10)

**Q6(b): Display Data Types and Non-Null Counts**

In [11]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      str
 2   Department           5 non-null      str
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      str
 7   Gender               5 non-null      str
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), str(4)
memory usage: 532.0 bytes

**Q6(c): Get Statistics**

In [12]:
df2.describe(include='all')

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
count,5.000000,5,5,5.000000,5.00000,5.000000,5,5,5.0,5.000000
unique,NaN,5,4,NaN,NaN,NaN,5,2,NaN,NaN
top,NaN,Alice,IT,NaN,NaN,NaN,2020-03-15,Male,NaN,NaN
freq,NaN,1,2,NaN,NaN,NaN,1,3,NaN,NaN
mean,103.000000,NaN,NaN,34.000000,60000.00000,7.400000,NaN,NaN,5500.0,4.100000
std,1.581139,NaN,NaN,5.612486,7905.69415,3.847077,NaN,NaN,1000.0,0.494975
min,101.000000,NaN,NaN,28.000000,50000.00000,3.000000,NaN,NaN,4500.0,3.500000
25%,102.000000,NaN,NaN,29.000000,55000.00000,4.000000,NaN,NaN,5000.0,3.800000
50%,103.000000,NaN,NaN,34.000000,60000.00000,8.000000,NaN,NaN,5000.0,4.000000
75%,104.000000,NaN,NaN,38.000000,65000.00000,10.000000,NaN,NaN,6000.0,4.500000
max,105.000000,NaN,NaN,41.000000,70000.00000,12.000000,NaN,NaN,7000.0,4.700000

**Q6(d): View Data**

In [13]:
df2.head(5)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [14]:
df2.tail(3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

**Q6(e-i): Average Salary**

In [15]:
print(df2['Salary'].mean())

60000.0

**Q6(e-ii): Total Bonus**

In [16]:
print(df2['Bonus'].sum())

27500

**Q6(e-iii): Youngest Employee**

In [17]:
print(df2['Age'].min())

28

**Q6(e-iv): Highest Rating**

In [18]:
print(df2['Rating'].max())

4.7

**Q6(f): Sort by Salary**

In [19]:
df2.sort_values(by=['Salary'],ascending=False,inplace=True)
df2

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

**Q6(g): Add Performance**

In [20]:
df2["Performance"] = df2["Rating"].apply(
    lambda x: "Excellent" if x >= 4.5
    else "Good" if x >= 4.0
    else "Average"
)
df2.head()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent

**Q6(h): Check Missing Values**

In [21]:
df2.isnull().sum()

Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
Performance            0
dtype: int64

**Q6(i): Rename Employee ID**

In [22]:
df2.rename(columns={"Employee_ID": "ID"}, inplace=True)
print(df2.columns)

Index(['ID', 'Name', 'Department', 'Age', 'Salary', 'Years_of_Experience',
       'Joining_Date', 'Gender', 'Bonus', 'Rating', 'Performance'],
      dtype='str')

**Q6(j-i): Find Experienced Employees**

In [23]:
df2[df2['Years_of_Experience']>5]

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

**Q6(j-ii): Find IT Employees**

In [24]:
df2[df2['Department']=='IT']

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

**Q6(k): Calculate Tax**

In [25]:
df2['Tax']=df2['Salary'].apply(lambda x : x*0.1)
df2

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance,Tax
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0

**Q6(l): Save Updated CSV**

In [26]:
df2.to_csv("employee_new.csv", index=False)
import os
print(os.path.exists("employee_new.csv"))

True